'use strict';

/**
 * General Score class
 * @property {Number} score Score achieved
 * @property {String} username Username of player
 * @property {Number} count300
 * @property {Number} count100
 * @property {Number} count50
 * @property {Number} countMiss
 * @property {Number} maxCombo
 * @property {Number} countKatu
 * @property {Number} countGeki
 * @property {Boolean} perfect True if maximum combo reached of map
 * @property {Number} enabledMods Bitwise flag of mods used generated by the C#
 * @property {Number} userId Player's user ID
 * @property {Date} date Date score set
 * @property {String} rank Rank of play, e.g. SS
 * @property {Number} pp PP value achieved
 */
class Score {
    constructor(data) {
        this.score = Number(data.score);
        this.username = data.username;
        this.count300 = Number(data.count300);
        this.count100 = Number(data.count100);
        this.count50 = Number(data.count50);
        this.countMiss = Number(data.countmiss);
        this.maxCombo = Number(data.maxcombo);
        this.countKatu = Number(data.countkatu);
        this.countGeki = Number(data.countgeki);
        this.perfect = !!data.perfect;
        this.enabledMods = Number(data.enabled_mods);
        this.userId = Number(data.user_id);
        this.date = new Date(data.date + ' GMT+0800');
        this.rank = data.rank;
        this.pp = Number(data.pp);
    }
}

module.exports = Score;